#
# Find argtable2 library
# 
# Maciej Maliborski 
# Mon Aug 30 18:20:41 2010
#

FIND_PATH(ARGTABLE2_INCLUDE_DIR argtable2.h /usr/include/ /usr/local/include/)

FIND_LIBRARY(ARGTABLE2_LIBRARY NAMES argtable2 PATH /usr/lib /usr/local/lib) 

IF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)
   SET(ARGTABLE2_FOUND TRUE)
ENDIF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)


IF (ARGTABLE2_FOUND)
   IF (NOT ARGTABLE2_FIND_QUIETLY)
      MESSAGE(STATUS "Found argtable2: ${ARGTABLE2_LIBRARY}")
   ENDIF (NOT ARGTABLE2_FIND_QUIETLY)
ELSE (ARGTABLE2_FOUND)
   IF (ARGTABLE2_FIND_REQUIRED)
     MESSAGE(FATAL_ERROR "Could not find argtable2")
   ENDIF (ARGTABLE2_FIND_REQUIRED)
ENDIF (ARGTABLE2_FOUND)


# SET(ARGTABLE2_EXE_LINKER_FLAGS "-largtable2")