#
# Find argtable2 library
# 
# Maciej Maliborski 
# Mon Aug 30 18:20:41 2010
#

FIND_PATH(ARGTABLE2_INCLUDE_DIR argtable2.h /usr/include/ /usr/local/include/)

FIND_LIBRARY(ARGTABLE2_LIBRARY NAMES argtable2 PATH /usr/lib /usr/local/lib) 

IF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)
   SET(ARGTABLE2_FOUND TRUE)
ENDIF (ARGTABLE2_INCLUDE_DIR AND ARGTABLE2_LIBRARY)


IF (ARGTABLE2_FOUND)
   IF (NOT Argtable2_FIND_QUIETLY)
      MESSAGE(STATUS "Found Argtable2: ${ARGTABLE2_LIBRARY}")
   ENDIF (NOT Argtable2_FIND_QUIETLY)
ELSE (ARGTABLE2_FOUND)
   IF (Argtable2_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Argtable2")
   ENDIF (Argtable2_FIND_REQUIRED)
ENDIF (ARGTABLE2_FOUND)
